on:
  pull_request:
    types: [opened]

name: Pull Request opened

jobs:
  assignToProject:
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    name: Assign PullRequest to Project
    runs-on: ubuntu-latest
    steps:
      - name: Assign PullRequest to Project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Backlog
          COLUMN: In progress
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author to PR
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  addLabelsByBranch:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeler
        uses: technote-space/pr-labeler-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id && startsWith(github.event.pull_request.head.ref, 'release/v')
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - name: Set running flag
        run: |
          if [[ ! -f package.json ]] || [[ $(< package.json jq -r '.version == null') == 'true' ]]; then
            echo "::set-env name=RUNNING::"
          fi

      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_PREFIX: release/
        if: env.RUNNING
